# Generated by Django 4.0.4 on 2022-05-24 13:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=128, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=128, verbose_name="address cont'd")),
                ('city', models.CharField(default='Zanesville', max_length=64, verbose_name='city')),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('zip_code', models.CharField(default='43701', max_length=5, verbose_name='zip code')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(null=True, upload_to='profile')),
                ('name', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='phone number should exactly be in 10 digits', regex='^\\d{10}$')])),
                ('department', models.IntegerField(choices=[(0, 'Trainee'), (1, 'Full Stack Developer'), (2, 'Frontend Developer'), (3, 'Backend Developer'), (4, 'Graphic Designer'), (5, 'Digital Marketer'), (6, 'Data Scientist')], default=0)),
                ('credit_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
