# Generated by Django 4.0.4 on 2022-05-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_1',
            new_name='address_line1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_2',
        ),
        migrations.AddField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, max_length=128, verbose_name='address2'),
        ),
    ]
