# Generated by Django 4.0.4 on 2022-05-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_employee_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
    ]
