# Generated by Django 4.0.4 on 2022-05-29 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='43701', max_length=7, verbose_name='zip code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.address'),
        ),
    ]
