# Generated by Django 4.0.4 on 2022-05-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_employee_employee_id_alter_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
