# Generated by Django 4.0.4 on 2022-05-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
